docs: Enable code examples in macros doc tests
CosmWasm/sylvia pull request #330
Opened 2024-03-20 17:06 UTC by jawoznia

2024-03-22 15:25 UTC, kulikthebird requested changes
Few text-related suggestions. Other than that lgtm

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
> +/// And similar `Query` and `Sudo` enum messages.
```suggestion
/// Similarly for `Query` and `Sudo` enum messages.
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
> +/// `#[sv::msg(msg_type)`. Msg attribute takes as its first argument type of message it is
```suggestion
/// `#[sv::msg(msg_type)]`. Msg attribute takes as its first argument type of message it is
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
> +/// you can do so using `sv::custom(msg=..., query=...)` attribute explained below.
```suggestion
/// you can do so using `#[sv::custom(msg=..., query=...)]` attribute explained below.
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
> +///   * `sudo` - this is sudo message variant
```suggestion
///   * `exec` - execute message variant
///   * `query` - query message variant
///   * `sudo` - sudo message variant
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
> +/// * `sudo` - this is sudo message variant
```suggestion
/// * `reply` - reply message variant
/// * `sudo` - sudo message variant
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
>  /// Messages structures are generated basing on specific implemented methods attributed with
```suggestion
/// Message structures are generated based on specific implemented methods attributed with
```

2024-03-22 15:25 UTC, kulikthebird commented on sylvia-derive/src/lib.rs
>  /// * `migrate` - this is migrate message variant
```suggestion
/// * `instantiate` - instantiation message handler. There should be always exactly one
/// * `exec` - execute message variant
/// * `query` - query message variant
/// * `migrate` - migrate message variant
```

2024-03-26 09:45 UTC, kulikthebird approved these changes

2024-03-26 12:53 UTC, merged

2024-04-02 12:32 UTC, jawoznia commented
#211